[build]
  command = "yarn build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "yarn start"
  port = 8888
  targetPort = 3000
  publish = "build"
  autoLaunch = true

[[redirects]]
  from = "/payment"
  to = "/.netlify/functions/payment"
  status = 200

[[redirects]]
  from = "/service-worker.js"
  to = "/.netlify/functions/service-worker"
  status = 200
  
# This ensures that React Router works properly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
