[build]
  command = "./build.sh"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.14.2"
  YARN_VERSION = "1.22.19"
  YARN_FLAGS = "--ignore-engines --ignore-optional --ignore-scripts --ignore-platform"

[dev]
  command = "yarn start"
  port = 8888
  targetPort = 3000
  publish = "build"
  autoLaunch = true

[[redirects]]
  from = "/payment"
  to = "/.netlify/functions/payment"
  status = 200

[[redirects]]
  from = "/service-worker.js"
  to = "/.netlify/functions/service-worker"
  status = 200
  
# This ensures that React Router works properly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
