const UserActionTypes = {
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    GITHUB_SIGN_IN_START: 'GITHUB_SIGN_IN_START',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    SEND_PASSWORD_RESET_FAILURE: 'SEND_PASSWORD_RESET_FAILURE',
    SEND_PASSWORD_RESET_START: 'SEND_PASSWORD_RESET_START',
    SEND_PASSWORD_RESET_SUCCESS: 'SEND_PASSWORD_RESET_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
};

export default UserActionTypes;
